### PR TITLE
Update to 1.12.0

### PR DESCRIPTION
**Pull request by maximlt**
geoviews 1.12.0

**Destination channel:** defaults

### Links

- [Upstream repository](https://github.com/holoviz/geoviews)
- [Upstream changelog/diff](https://github.com/holoviz/geoviews/compare/v1.11.1...v1.12.0?short_path=60f61ab#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7)

### Explanation of changes:

- https://github.com/conda-forge/geoviews-feedstock/pull/38/files

### CODE REVIEW

**Review by cbouss — APPROVED** [review]
LGTM
@maximlt Should matplotib-base be added to geoviews' output?

**Review by Jrice1317 — APPROVED** [review]
LGTM, but I'm also curious about Charles' comment RE: matplotlib-base

**Comment by maximlt** [comment]
> LGTM @maximlt Should matplotib-base be added to geoviews' output?

@cbouss matplotlib is not a required dependency of GeoViews. Are you asking because Matplotlib is mentioned in the descriptions?

**Comment by cbouss** [comment]
> > LGTM @maximlt Should matplotib-base be added to geoviews' output?
> 
> @cbouss matplotlib is not a required dependency of GeoViews. Are you asking because Matplotlib is mentioned in the descriptions?

I am asking because the feedstock has two outputs: geoviews-core (without extra dependencies) and geoviews (with recommended dependencies). matplotlib is in the recommended dependencies here: https://github.com/holoviz/geoviews/blob/v1.12.0/setup.py#L113 but not in the recipe.

Should it be added, or should we leave the recipe as-is?

**Comment by maximlt** [comment]
Good question!

> Should it be added, or should we leave the recipe as-is?

Fine-tuning/aligning the recommended dependencies is something we need to do for our packages in general. In this case, I prefer postponing, for now, the decision to add `matplotlib-base`.

**Pull request merged**
